//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiClientes.Resources; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class ErrorResponseMessages {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ErrorResponseMessages() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiClientes.Resources.ErrorResponseMessages", typeof(ErrorResponseMessages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ocorreu um erro durante a operação de Remoção do Cadastro!.
    /// </summary>
    internal static string ErrorDuringDelete {
        get {
            return ResourceManager.GetString("ErrorDuringDelete", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ocorreu um erro durante a operação de Cadastro!.
    /// </summary>
    internal static string ErrorDuringInsertion {
        get {
            return ResourceManager.GetString("ErrorDuringInsertion", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ocorreu um erro durante a operação de Busca!.
    /// </summary>
    internal static string ErrorDuringSearch {
        get {
            return ResourceManager.GetString("ErrorDuringSearch", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ocorreu um erro durante a operação de Alteração do Cadastro!.
    /// </summary>
    internal static string ErrorDuringUpdate {
        get {
            return ResourceManager.GetString("ErrorDuringUpdate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to O valor &quot;{0}&quot; não corresponde a um CPF nem CNPJ válido!.
    /// </summary>
    internal static string InvalidDocumentNumberError {
        get {
            return ResourceManager.GetString("InvalidDocumentNumberError", resourceCulture);
        }
    }
}
